---
title: "SLR"
output: html_document
date: "2023-07-26"
---

```{r setup, include=FALSE}
library(terra)
library(tidyverse)
library(here)

rast_base_10km_file <- terra::rast(here('_spatial/rast_base_mol_10km.tif'))

```


```{r}

file_rename <-data.frame(filename = c(
  "CMIP6 - Sea level rise (SLR) Change meters - Long Term (2081-2100) SSP1-2.6 (rel. to 1995-2014) - Annual.tiff", 
  "CMIP6 - Sea level rise (SLR) Change meters - Long Term (2081-2100) SSP2-4.5 (rel. to 1995-2014) - Annual .tiff", 
  "CMIP6 - Sea level rise (SLR) Change meters - Long Term (2081-2100) SSP3-7.0 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Long Term (2081-2100) SSP5-8.5 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Medium Term (2041-2060) SSP1-2.6 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Medium Term (2041-2060) SSP2-4.5 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Medium Term (2041-2060) SSP3-7.0 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Medium Term (2041-2060) SSP5-8.5 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Near Term (2021-2040) SSP1-2.6 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Near Term (2021-2040) SSP2-4.5 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Near Term (2021-2040) SSP3-7.0 (rel. to 1995-2014) - Annual .tiff",
  "CMIP6 - Sea level rise (SLR) Change meters - Near Term (2021-2040) SSP5-8.5 (rel. to 1995-2014) - Annual .tiff"),
  scenario = c("ssp126", "ssp245", "ssp370", "ssp585", "ssp126", "ssp245", "ssp370", "ssp585", "ssp126", "ssp245", "ssp370", "ssp585"),
  timeframe = rep(c("long-term", "medium-term", "near-term"), each=4))

raw_data <- "/home/shares/ohi/stressors_2021/_raw_data/slr_ipcc"
save_data_location <- "/home/shares/ohi/stressors_2021/_dataprep/slr"
file_list <- list.files(raw_data, pattern="tif", full=TRUE)

for(file in file_rename$filename){ # file = file_rename$filename[1]
  
  save_name <- paste0("slr_", file_rename$scenario[file_rename$filename==file], "_",
                    file_rename$timeframe[file_rename$filename==file], ".tif")
  
  tmp <- rast(file.path(raw_data, file))
  tmp_proj <- project(tmp, rast_base_10km_file, method="bilinear")

  tmp_proj_gf <- tmp_proj

for(i in 1:20){
  i=1+i
tmp_proj_gf <- terra::focal(tmp_proj_gf, w=3, fun=mean, na.rm=TRUE, na.policy="only")
cat(i, "\n")
}

masked_gf <- tmp_proj_gf*total_area
    ## plot(masked_gf - tmp_proj)

writeRaster(masked_gf, file.path(save_data_location, "raw", save_name), overwrite=TRUE)

rescaled <- ifel(masked_gf > 1, 1, masked_gf)
rescaled <- ifel(rescaled < 0, 0, rescaled)
writeRaster(rescaled, file.path(save_data_location, "rescaled", save_name), overwrite=TRUE)
}


```

Crop the rescaled rasters to within 10 km from shoreline
```{r}

ocean_raw <- terra::rast(here('_spatial/ocean_area_mol.tif'))
ocean_template <- ocean_raw
ocean_template[ocean_template>0] <- 1
terra::plot(ocean_template)

coast <- terra::ifel(ocean_raw >0 & ocean_raw<1, 1, NA)
terra::global(coast, "sum", na.rm=TRUE)

## masking out that outer ring!
boundary_mask <- rast(nrow=1814, ncol=3617, xmin=-180, xmax=180, ymin=-90, ymax=90)
values(boundary_mask) <- 1
boundary_mask_mol <- terra::project(boundary_mask, "+proj=moll", res=10000)
boundary_mask_mol <- extend(boundary_mask_mol, ext(coast), fill=NA)
boundary_mask_mol <- resample(boundary_mask_mol, coast, method="near")
inner_boundary <-  boundaries(boundary_mask_mol, inner=TRUE, falseval=0)
global_mask <- ifel(inner_boundary==0, 1, NA)
coast <- coast*global_mask

files_list <- list.files("/home/shares/ohi/stressors_2021/_dataprep/slr/rescaled", full=TRUE)

for(file in files_list){ # file = files_list[1]
  tmp_name <- basename(file)
  tmp <- rast(file) *coast 
#  check <- ifel(!is.na(tmp), 1, NA)
#  global(check, "sum", na.rm=TRUE)
  writeRaster(tmp, sprintf("/home/shares/ohi/stressors_2021/_dataprep/slr/rescaled_crop/%s",
                           tmp_name), overwrite=TRUE)
  
}

```


## make current
Current is all zero values, which probably isn't correct because sea level has risen in recent years.

```{r}
current <- coast
plot(current)
current <- ifel(current == 1, 0, NA)
plot(current)
 writeRaster(current, "/home/shares/ohi/stressors_2021/_dataprep/slr/rescaled_crop/slr_ssp126_current.tif", overwrite=TRUE)
 writeRaster(current, "/home/shares/ohi/stressors_2021/_dataprep/slr/rescaled_crop/slr_ssp245_current.tif", overwrite=TRUE)
writeRaster(current, "/home/shares/ohi/stressors_2021/_dataprep/slr/rescaled_crop/slr_ssp370_current.tif", overwrite=TRUE)
writeRaster(current, "/home/shares/ohi/stressors_2021/_dataprep/slr/rescaled_crop/slr_ssp585_current.tif", overwrite=TRUE)

```