---
title: "Untitled"
output: html_document
date: "2024-03-20"
---

step1: extract biomass data for regions.
step2: data and models to see if we can predict changes to fisheries pressures
This is an information gathering step that can be skipped. 

```{r setup, include=FALSE}

library(countrycode)
library(tidyverse)
library(here)

pressure_avg <- read_csv(here("prep/fisheries/data/region_biomass_trends.csv")) %>%
  mutate(ant_typ = ifelse(!is.na(uninhabited), "eez_uninhabited", ant_typ))

biomass_rgn <- read_csv(here("prep/fisheries/data/country_biomass_2000_2010.csv"))

## some general patterns:
ggplot(pressure_avg, aes(x=avg_percent_change, group=ant_typ, fill=ant_typ)) +
  geom_histogram()
ggplot(pressure_avg, aes(x=slope, group=ant_typ, fill=ant_typ)) +
  geom_histogram()
ggplot(filter(pressure_avg, prop_biomass<2), aes(x=prop_biomass, group=ant_typ, fill=ant_typ)) +
  geom_histogram()

hs_historic <- pressure_avg %>% 
  group_by(ant_typ) %>%
  summarize(historic_biomass = sum(historic_1900, na.rm=TRUE))

pressure_avg %>% 
  group_by(ant_typ) %>%
  summarize(historic_biomass = sum(biomass_2010, na.rm=TRUE))

```


Combining the high seas and ccamlr regions to get future predictions.
```{r}

hs_biomass_mean <- biomass_rgn %>%
  filter(ant_typ %in% c("fao", "eez-ccamlr")) %>%
  select(year, biomass) %>%
  group_by(year) %>%
  summarize(biomass=sum(biomass, na.rm=TRUE))

ggplot(hs_biomass_mean, aes(x=year, y=biomass)) + 
  geom_line() 

check <- hs_biomass_mean %>%
  arrange(year) %>%
  mutate(yearly_percent_change = (biomass - lag(biomass))/lag(biomass)) 

ggplot(check, aes(x=year, y=yearly_percent_change)) + 
  geom_line() 

hs_avg_change <- hs_biomass_mean %>%
  mutate(yearly_percent_change = (biomass - lag(biomass))/lag(biomass)) %>%
    summarize(start_biomass = biomass[year==min(2000)],
            end_biomass = biomass[year == max(year)],
            start_year = min(year),
            end_year = max(year),
            avg_biomass = mean(biomass),
            biomass_2005 = biomass[year==2005],
            biomass_2010 = biomass[year==2010],
            sd_annual_rate_change = sd(yearly_percent_change, na.rm=TRUE)) %>%
  mutate(duration = end_year - start_year,
         annual_rate_change = ((end_biomass / start_biomass)^(1 / duration) - 1)) %>%
  select(-duration)

## add in the historic biomass
hs_avg_change$historic_biomass <- sum(hs_historic$historic_biomass[hs_historic$ant_typ %in% c("eez-ccamlr", "fao")])
hs_avg_change$prop_biomass <- hs_avg_change$biomass_2010/hs_avg_change$historic_biomass


```


Creating the high seas, region specific data:
```{r}

hs_scenario <- biomass_rgn %>%
  filter(ant_typ %in% c("fao", "eez-ccamlr")) %>%
  select(rgn_id, year, rgn_nam)

scenario_year_template <- expand.grid(scenario = c("SSP1", "SSP2", "SSP3", "SSP4", "SSP5"),
                                      year = 2000:2100,
                                      rgn_id = hs_scenario$rgn_id)

hs_scenario <- left_join(scenario_year_template, hs_scenario, by=c("year", "rgn_id"))

```